//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceDBAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int id { get; set; }
        public string userName { get; set; }
        public string mailID { get; set; }
        public string phoneNumber { get; set; }
        public string skillSet { get; set; }
        public string hobby { get; set; }
    }
}
